# Generated by Django 6.0.5 on 2026-06-20 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='teams.department'),
            preserve_default=False,
        ),
    ]
