# Generated by Django 6.0.5 on 2026-07-09 14:45

from django.db import migrations, models


def dedupe_full_names(apps, schema_editor):
    """Make existing (first_name, last_name) pairs unique before the constraint
    lands. Duplicates (e.g. seeded test users sharing a name) get a numeric
    suffix on the given name so the AddConstraint below can't fail on old data.
    """
    User = apps.get_model("users", "User")
    seen = set()
    for user in User.objects.exclude(first_name="").exclude(last_name="").order_by("id"):
        key = (user.first_name, user.last_name)
        if key not in seen:
            seen.add(key)
            continue
        base, n = user.first_name, 2
        while (f"{base} ({n})"[:100], user.last_name) in seen:
            n += 1
        user.first_name = f"{base} ({n})"[:100]
        user.save(update_fields=["first_name"])
        seen.add((user.first_name, user.last_name))


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teams', '0005_team_department'),
        ('users', '0007_user_avatar'),
    ]

    operations = [
        migrations.RunPython(dedupe_full_names, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('first_name', ''), _negated=True), models.Q(('last_name', ''), _negated=True)), fields=('first_name', 'last_name'), name='unique_full_name'),
        ),
    ]
