# Generated by Django 6.0.5 on 2026-07-05 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasklink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TaskStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done'), ('overdue', 'Overdue')], max_length=20)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done'), ('overdue', 'Overdue')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_status_changes', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='tasks.task')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
    ]
