import { test, expect } from "@playwright/test";

import { ADMIN, ADMIN_DISPLAY_NAME } from "./admin";
import { login, createTask } from "./helpers";

// A tiny PNG generated by Pillow — CRC-valid so the backend's Pillow verify()
// accepts it (a hand-rolled minimal PNG can pass `file` but fail verify()).
const PNG_TINY = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAFElEQVR4nGOU07BhgAEmBiSAmwMAGkoAipX98uMAAAAASUVORK5CYII=",
  "base64",
);

test("add and remove a link on a task", async ({ page }) => {
  await login(page, ADMIN);
  await createTask(page, {
    title: `link ${Date.now()}`,
    assigneeLabel: ADMIN_DISPLAY_NAME,
  });

  await page.locator("#link-url").fill("https://example.com/spec");
  await page.locator("#link-label").fill("Spec doc");
  await page.getByRole("button", { name: "Thêm" }).click();

  const link = page.getByRole("link", { name: /Spec doc/ });
  await expect(link).toBeVisible();
  await expect(link).toHaveAttribute("href", "https://example.com/spec");

  await page.getByRole("button", { name: "Xoá liên kết" }).click();
  await expect(link).toHaveCount(0);
});

test("upload and remove an attachment on a task", async ({ page }) => {
  await login(page, ADMIN);
  await createTask(page, {
    title: `att ${Date.now()}`,
    assigneeLabel: ADMIN_DISPLAY_NAME,
  });

  await page.locator('input[type="file"]').setInputFiles({
    name: "shot.png",
    mimeType: "image/png",
    buffer: PNG_TINY,
  });
  await page.getByPlaceholder("Chú thích (tuỳ chọn)").fill("Ảnh chụp");
  await page.getByRole("button", { name: "Tải lên" }).click();

  const thumb = page.getByRole("img", { name: "Ảnh chụp" });
  await expect(thumb).toBeVisible();

  await page.getByRole("button", { name: "Xoá đính kèm" }).click();
  await expect(thumb).toHaveCount(0);
});
